language: csharp
solution: SalesTaxes.sln
install:
  - nuget restore  SalesTaxes.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SalesTaxes.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SalesTaxes.Tests/bin/Release/SalesTaxes.Tests.dll
